client_id = "e1061aefe8f8729bf44a60f7121719b5"
application_url = "https://pyc-membership-backend.onrender.com"
embedded = true
name = "PYC Membership Backend"

[access_scopes]
scopes = "read_orders,read_customers,write_customers"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = ["orders/paid"]

[auth]
redirect_urls = ["https://pyc-membership-backend.onrender.com/auth/callback"]

[build]
automatically_update_urls_on_dev = true